### ISSUE TITLE
Tried to translate on mobile

### ISSUE THREAD

**Issue by uhlhosting** [keepassium/KeePassium-L10n#1]
![image](https://user-images.githubusercontent.com/6324047/108491761-9f6f3300-72a4-11eb-93ae-da7279f5786d.png)

Seems is not working.

**Comment by keepassium** [comment]
It was probably a temporary glitch. Try to reload the page.
![IMG_0673](https://user-images.githubusercontent.com/38399598/108506586-55dd1300-72b9-11eb-9a50-a7456251ae31.PNG)
